name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  
jobs:
  build:
    name: Build C++ Project on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0

      - name: Get Gitmodules (Recursively)
        run: git submodule update --init --recursive
            
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/D_CRT_SECURE_NO_WARNINGS"

      - name: Build project
        run: cmake --build build --config Release
