name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:
  
jobs:
  build:
    name: Build C++ Project on Windows
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0
            
      - name: Get Gitmodules (Recursively)
        run: git submodule update --init --recursive

      - name: Build the Release Build
        run: ./install.bat /skipstart /verbose