name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:  
  release:
    name: 🚀 Windows Release
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0

      - name: Get Gitmodules (Recursively)
        run: git submodule update --init --recursive

      - name: Install the Release Build
        run: ./install.bat /skipstart /verbose /clean-pb

      - name: Zip the Release Directory
        working-directory: ./build
        run: powershell Compress-Archive -Path * -DestinationPath ../COMP-345.zip

      - name: Upload Files to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./COMP-345.zip
          asset_name: COMP-345.zip
          asset_content_type: application/zip